version: "3"

services:
  web:
    build:
      context: ./web
      dockerfile: development.Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
    volumes:
      - ./web:/usr/src/web
    depends_on:
      - api
      - db
  api:
    build:
      context: ./api
      dockerfile: development.Dockerfile
    env_file:
      - ./api/.env.development
    environment:
      NODE_ENV: development
      DB_HOST: db
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/api
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    env_file:
      - db/sqlserver.env
      - db/sapassword.env
    user: root
    volumes:
      - sqlsystem:/var/opt/mssql/
      - sqldata:/var/opt/sqlserver/data
      - sqllog:/var/opt/sqlserver/log
      - sqlbackup:/var/opt/sqlserver/backup

volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:
